### ISSUE TITLE
Nhận xét đồ án

### ISSUE THREAD

**Issue by vohieu00** [vohieu00/DataScience#1]
Thân gửi,
Hiện tại nhóm đã hoàn thành xong đồ án cuối kỳ môn Nhập môn Khoa học dữ liệu, mời thầy và các bạn nhận xét, đóng góp ý kiến.
Chân thành cảm ơn.

**Comment by ngocbinh53** [comment]
1712293- Nguyễn Ngọc Bình
Chào bạn, mình thấy bạn làm khá tốt và mình có vài nhận xét như sau: 
 -  Để có thể đọc mà hiểu những gì bạn làm ở file notebook cần mở slide lên, mà mình nghĩ notebook cũng là một trang trình bày khá hay nên nếu có thể bạn trình bày cụ thể trong file notebook thì hay hơn nhiều.
  - Trong quá trình có việc thu thập dữ liệu, mình chưa thấy đoạn code nào trình bày nó sẽ thu thập sau, cá nhân mình thì nếu không tin tưởng file dữ liệu bạn thu thập thì mình muốn kiểm tra bạn thu thập như thế nào và bạn thu thập bằng API hay parse HTML. Và bạn không cho thấy dữ liệu bạn như thế nào, mỗi dòng có thuộc tính gì, bạn khám phá được sao, kiểu như phải cho người xem thấy à cái này như thế này, dữ liệu nó có gì abc gì đó nên mình xóa sao á.
 -  Hơn nữa, bạn thiếu phần kinh nghiệm bài học với khó khắn khi làm đồ án.
Mình có đôi lời góp ý vậy, hy vọng góp một chút để bạn hoàn thiện đồ án tốt hơn.
Cảm ơn bạn.

**Comment by chipmoonchanged1** [comment]
Chào các bạn, mình đã xem qua bài của các bạn và có một vài nhận xét theo cá nhân mình như sau:

- Mình thấy dữ liệu của các bạn khá nhỏ, và thuộc tính hình như lên tới 32 cột, mình nghĩ mô hình sẽ khó học
- Nếu bài có thêm chú thích và giải thích thêm ở từng bước thì chắc sẽ tốt hơn và dễ theo dõi hơn 

Cảm ơn các bạn đã đọc góp ý của mình, chúc các bạn hoàn thành tốt đồ án <333

**Comment by vohieu00** [comment]
Cảm ơn các anh chị và các bạn đã góp ý, nhóm mình sẽ tiến hành hoàn thiện hơn, Thân

**Comment by RonnienNguyen** [comment]
Chào các bạn,
Mình thấy đồ án của nhóm mình có phân nhóm và thông tin rõ về giá thành của laptop và PC.
Điều này rất tốt với tầng lớp sinh viên, học sinh của mình để lựa chọn dòng laptop.
Ngoài ra mình nghĩ nên kham khảo giá laptop ở các trang lớn như Tin học ngôi sao, GearVN, Xgear để so sánh với dữ liệu ở Phong Vũ (vì dữ liệu giá ở Phong Vũ khác mắc hơn so với thị trường).
Nếu so sánh được giá của các trang khác nhau và đưa ra quyết định nên mua dòng nào thì sẽ tốt hơn (sau khi đối chiếu hiệu năng, cấu thành).

Chúc các bạn hoàn thành đồ án tốt <3

**Comment by trucnguyen13** [comment]
Chào các bạn, 
Mình bên nhóm 26, tình cờ ý tưởng cũng giống hệt bên nhóm bạn( cùng trang phongvu). Bên mình khâu tiền xử lý dữ liệu rất kỹ, như chắc lọc các phần quan trọng và các cột có dạng số thì chuyển về numerical hết, nên số lượng thuộc tính đặc trưng còn rất ít, khoảng 10 thuộc tính. Nhưng khi áp dụng mô hình MLPRegressor thì độ lỗi khá cao, không như bên bạn, nên bên mình đã áp dụng các mô hình của "Linear Models" thì cho kết quả khá tốt. Mình cũng không hiểu tại sao, có thể mình chưa hiểu rõ về cách áp dụng mô hình nào cho hợp lý hay số cột đặc trưng của mình còn quá ít. Mình đã tìm hiểu về phần làm của nhóm bạn, nhóm bạn áp dụng sẵn luôn các dữ liệu từ website. Nên khi tiền xử lý cuối cùng, mình thấy "preprocessed_train_X.shape" bên bạn lên tới (545, 1673), rất là lớn so vơi bên mình( tầm (400,30)), nhưng khi vào mô hình thì độ lỗi khá thấp. Mình đã áp dụng mô hình đơn giản "LinearRegression" và chỉnh "labels" lên mức cao thì cho ra kết quả độ lỗi tập test cuối cùng thấp hơn 10%. Có vẻ độ lỗi sẽ còn giảm nhiều nếu tìm được mô hình tối ưu và điểu chỉnh nhiều tham số đầu vào hợp lý.
Dù góp ý hơi muộn,vì hôm nay làm xong mới có thời gian đi tìm hiểu cách làm các nhóm khác, chung lại vẫn là thảo luận để giúp nhau hiểu rõ hơn về đồ án.
Chúc các bạn thi tốt trong kỳ thi cuối kỳ <3
